### ISSUE TITLE
Daily log questions

### ISSUE THREAD

**Issue by docsbydesign** [MercerU-TCO/CTS#11]
Todo los campos de la cabeza.
Cada formulario es por medico (Profesional de salud)
Hay clases de profesional? (medico/a? enfermera? terapista? otro?

Columnos:
1) Numero de historia clinica: clinic ID del paciente?
2) Numero de identidad del paciente: cedula?
3) "Paciente" ??
4) "Localidad" = Barrio, Colonia, Aldea (Neighborhood)?
5) Condicion?
6) Referencia: Nombre, codigo?

**Comment by rbwatson** [comment]
numero de Histroria clinica = ?
Patient ID = folder ID
Patient = new patient or subsequent visit
Localidad = neighborhood
condicion = new or subsequent diagnosis
