### ISSUE TITLE
Terminology questions

### ISSUE THREAD

**Issue by docsbydesign** [MercerU-TCO/CTS#13]
* Admit, Discharge, and what's between them?
* Procedencia (what fields? Address1 & 2, Barrio, Municipio, Departamento, ?)
* Contact info: email?
* ICD-10 codes used?

**Comment by rbwatson** [comment]
* Admit, Discharge, and what's between them? 
    * Admit, admitted, discharge, discharged
    * Admitir, admitido, dar de alta, dado de alta
* Procedencia (what fields? Address1 & 2, Barrio, Municipio, Departamento, ?)
    * yes
* Contact info: email?
    * ?
* ICD-10 codes used? 
    * CIE-10 (in spanish)
