### ISSUE TITLE
VAL: UTF-8 BOM char causing HTML validation errors

### ISSUE THREAD

**Issue by rbwatson** [MercerU-TCO/CTS#26]
* Error: Non-space characters found without seeing a doctype first. Expected <!DOCTYPE html>.
* Error: Element head is missing a required instance of child element title.
* Error: Stray doctype.
* Error: Stray start tag html.

Looks like an error in the DOCTYPE line

clinicDash.php
ptInfo.php
ptResults.php
visitOpen.php

Check ALL files for BOM character...

**Comment by docsbydesign** [comment]
https://github.com/MercerU-TCO/CTS/commit/0f9a973dcf6cd4f8e248485e6db707e56b48297e
Tested OK
