### ISSUE TITLE
Update date/time pickers to use polyfill or other, smarter widget.

### ISSUE THREAD

**Issue by docsbydesign** [MercerU-TCO/CTS#29]
In these files (at least)
* ptImageEdit.php
* visitOpen.php

**Comment by rbwatson** [comment]
The default input fields on the chromium browser of the Pi seem to work well. They might be OK, but if there are better date/time pickers available, they should be investigated some.

**Comment by docsbydesign** [comment]
The default input boxes on the Raspberry PI are good enough for the field test. If there's an issue, this can be reviewed after the field test.
