### ISSUE TITLE
Add/test support for barcode label printer(s)

### ISSUE THREAD

**Issue by rbwatson** [MercerU-TCO/CTS#48]
support printing Patient ID barcode labels to affix to forms, folders, etc.

**Comment by rbwatson** [comment]
Tested printer support for Labelwriter 450
Seems to be installed with CUPS driver.
supports printing from web browser and open office apps.
More work to integrate with patient system required: e.g. how to create/send label content to printer from browser.

**Comment by docsbydesign** [comment]
code39.php is tested and
fixed in reports branch.

**Comment by rbwatson** [comment]
Barcode on forms prints fine for now.
