### ISSUE TITLE
Write API and UI-shim errors to a log file

### ISSUE THREAD

**Issue by docsbydesign** [MercerU-TCO/CTS#53]
Right now, they're hidden or they show up in random places.

**Comment by docsbydesign** [comment]
Things to log:
* param list
* SQL errors
* date/time
* script
* referrerURL
* user agent (?)
* username (if available)

**Comment by rbwatson** [comment]
standardize format of data from error to include basically what used to be returned as an error block:
* httpResponse
* httpReason
* error structure (varies)
