### ISSUE TITLE
Create system reset script

### ISSUE THREAD

**Issue by docsbydesign** [MercerU-TCO/CTS#58]
A script to clear the database and app files and reset to an empty DB.
It should:
1. do a ```git pull origin master``` to get the current app files.<br>You can also do a  ```git pull origin <release>``` where <release> is the tag of the specific release build.
1. Archive and clear any log files in the  ```/var/log/cts``` folder
2. Empty and, if necessary, recreate the image folder ```/var/local/images``` and ```var/local/deleted```
3. Empty the ```/var/www/html``` folder and:
  * reload the uploaded files from ```~/CTS/web```
  * set file owner and access mode for copied files
  * set password in ```dbPass.php```
4. Create/reset the database
  * ```cd ~/CTS/sql```
  * ```sudo mysql -uroot -pPASSWORD < cts_def.sql```
4. Prompt to install test data:
  * ```cd ~/CTS/tools```
  * ```python3 create-patients.py <PT ID prefix string> <number of patients to create>```
  * ```python3 create-visits.py <number of history days> <number of visits per day>```
  * ```python3 create-admits.py <number of patients currently in the clinic>```

**Comment by docsbydesign** [comment]
Documentation might be sufficient for now...

**Comment by rbwatson** [comment]
Created Wiki Page: https://github.com/MercerU-TCO/CTS/wiki/System-reset-procedure
