### ISSUE TITLE
Create script to lock down global access to system files

### ISSUE THREAD

**Issue by docsbydesign** [MercerU-TCO/CTS#66]
1. Identify the folders and files on the standard Raspberry Pi Linux distribution that regular users should not have access to and those to which they should only have read or read and execute permission to.
2. Create a script to remove WORLD (ALL) access to them.
3. Test piClinic functionality to make sure nothing broke.

If this requires the creation of new user groups, note that in the solution.

**Comment by docsbydesign** [comment]
See also #70

**Comment by rbwatson** [comment]
Rolled into #94
