### ISSUE TITLE
Lockdown Apache & PHP (and other?) web-server settings

### ISSUE THREAD

**Issue by docsbydesign** [MercerU-TCO/CTS#70]
E.g. as described in these:
* [https://www.acunetix.com/blog/articles/10-tips-secure-apache-installation/](https://www.acunetix.com/blog/articles/10-tips-secure-apache-installation/)
* [https://www.tecmint.com/apache-security-tips/](https://www.tecmint.com/apache-security-tips/)
* [https://www.owasp.org/index.php/PHP_Configuration_Cheat_Sheet](https://www.owasp.org/index.php/PHP_Configuration_Cheat_Sheet)
* and others (to make sure)

**Comment by rbwatson** [comment]
Rolled into #94
