### ISSUE TITLE
Update base OS images to latest Raspbian build

### ISSUE THREAD

**Issue by rbwatson** [MercerU-TCO/CTS#74]
The Nov 29 build of Raspian for the pi was released.
Update the system software to this version

https://www.raspberrypi.org/downloads/raspbian/

**Comment by rbwatson** [comment]
The new build should also include multi-user support (#30)  with user and admin (root) accounts.
Also, if possible, include the file access definitions described in #50, #66, #67.

**Comment by docsbydesign** [comment]
Fixed. Current OS image and setup instructions use recent OS build and support multi-user access.
#50, #66, and #67 are still open
