### ISSUE TITLE
Add support for "family/folder ID" field

### ISSUE THREAD

**Issue by rbwatson** [MercerU-TCO/CTS#95]
Add to:
* patient add/edit info
* search field/logic
* search results (should be automatic)
* advanced search page (add field)

? Maybe a family summary page?
? modified search results page (e.g. include past 3-5 visits in results?)

**Comment by docsbydesign** [comment]
Fixed in ata-entry branch

**Comment by docsbydesign** [comment]
Merged PR of ata-entry branch
